services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./web/static:/app/static
    volumes:
      - ./nginx/keramicheskiy.conf:/etc/nginx/conf.d/keramicheskiy.conf
      - ./nginx/krmch.conf:/etc/nginx/conf.d/krmch.conf
      # - ./web/static:/app/static
      - /etc/letsencrypt:/etc/letsencrypt    # Монтирование Let's Encrypt
    restart: always
