services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./web/static:/app/static
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      # - ./web/static:/app/static
      - static-data:/usr/share/nginx/html/static
      - /etc/letsencrypt:/etc/letsencrypt    # Монтирование Let's Encrypt
    restart: always
    networks:
      - nginx_network

volumes:
  static-data:

networks:
  nginx_network:
    external: true
