services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - static-data:/static
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    networks:
      - nginx_network

volumes:
  static-data:
    external: true

networks:
  nginx_network:
    external: true
